In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
text1 ='''Tracy loves writing about data science.'''

In [4]:
text2 = '''Tracy loves writing for medium publications.'''     

In [5]:
text3 = '''Tracy loves studying Python programming.'''

In [6]:
text4 = '''Tracy loves entering Kaggle competitions.'''

In [8]:
corpus = [text1, text2, text3, text4]
corpus


['Tracy loves writing about data science.',
 'Tracy loves writing for medium publications.',
 'Tracy loves studying Python programming.',
 'Tracy loves entering Kaggle competitions.']

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
count_vec = CountVectorizer()

In [11]:
word_count_vec = count_vec.fit_transform(corpus)
word_count_vec.shape

(4, 15)

In [12]:
print(count_vec.get_feature_names())

['about', 'competitions', 'data', 'entering', 'for', 'kaggle', 'loves', 'medium', 'programming', 'publications', 'python', 'science', 'studying', 'tracy', 'writing']


C:\Users\User\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [13]:
print("Vocabulary: ", count_vec.vocabulary_)

Vocabulary:  {'tracy': 13, 'loves': 6, 'writing': 14, 'about': 0, 'data': 2, 'science': 11, 'for': 4, 'medium': 7, 'publications': 9, 'studying': 12, 'python': 10, 'programming': 8, 'entering': 3, 'kaggle': 5, 'competitions': 1}


In [14]:
print(word_count_vec.toarray())

[[1 0 1 0 0 0 1 0 0 0 0 1 0 1 1]
 [0 0 0 0 1 0 1 1 0 1 0 0 0 1 1]
 [0 0 0 0 0 0 1 0 1 0 1 0 1 1 0]
 [0 1 0 1 0 1 1 0 0 0 0 0 0 1 0]]


In [15]:
# Use the content column instead of our single text variable
matrix = count_vec.fit_transform(corpus)
counts = pd.DataFrame(matrix.toarray(), index=['doc1','doc2', 'doc3', 'doc4'],columns=count_vec.get_feature_names())
counts
     

about  competitions  data  entering  for  kaggle  loves  medium  \
doc1      1             0     1         0    0       0      1       0   
doc2      0             0     0         0    1       0      1       1   
doc3      0             0     0         0    0       0      1       0   
doc4      0             1     0         1    0       1      1       0   

      programming  publications  python  science  studying  tracy  writing  
doc1            0             0       0        1         0      1        1  
doc2            0             1       0        0         0      1        1  
doc3            1             0       1        0         1      1        0  
doc4            0             0       0        0         0      1        0

# TfidfTransformer

In [16]:
from sklearn.feature_extraction.text import TfidfTransformer 

tf_transformer = TfidfTransformer(use_idf=True).fit(matrix)
word_count_vec_tf = tf_transformer.transform(matrix)
word_count_vec_tf.shape

(4, 15)

In [17]:
df1 = pd.DataFrame(word_count_vec_tf.toarray(),columns=count_vec.get_feature_names(),index=['doc1','doc2', 'doc3', 'doc4'])
df1

C:\Users\User\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


about  competitions      data  entering       for    kaggle  \
doc1  0.489924      0.000000  0.489924  0.000000  0.000000  0.000000   
doc2  0.000000      0.000000  0.000000  0.000000  0.489924  0.000000   
doc3  0.000000      0.000000  0.000000  0.000000  0.000000  0.000000   
doc4  0.000000      0.531146  0.000000  0.531146  0.000000  0.531146   

         loves    medium  programming  publications    python   science  \
doc1  0.255662  0.000000     0.000000      0.000000  0.000000  0.489924   
doc2  0.255662  0.489924     0.000000      0.489924  0.000000  0.000000   
doc3  0.277174  0.000000     0.531146      0.000000  0.531146  0.000000   
doc4  0.277174  0.000000     0.000000      0.000000  0.000000  0.000000   

      studying     tracy   writing  
doc1  0.000000  0.255662  0.386261  
doc2  0.000000  0.255662  0.386261  
doc3  0.531146  0.277174  0.000000  
doc4  0.000000  0.277174  0.000000

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(df1[0:1], df1)

array([[1.        , 0.27992449, 0.14172606, 0.14172606]])

# TfidfVectorizer

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
trsfm=vectorizer.fit_transform(corpus)
data = pd.DataFrame(trsfm.toarray(),columns=vectorizer.get_feature_names(),index=['doc1','doc2', 'doc3', 'doc4'])
data

C:\Users\User\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


about  competitions      data  entering       for    kaggle  \
doc1  0.489924      0.000000  0.489924  0.000000  0.000000  0.000000   
doc2  0.000000      0.000000  0.000000  0.000000  0.489924  0.000000   
doc3  0.000000      0.000000  0.000000  0.000000  0.000000  0.000000   
doc4  0.000000      0.531146  0.000000  0.531146  0.000000  0.531146   

         loves    medium  programming  publications    python   science  \
doc1  0.255662  0.000000     0.000000      0.000000  0.000000  0.489924   
doc2  0.255662  0.489924     0.000000      0.489924  0.000000  0.000000   
doc3  0.277174  0.000000     0.531146      0.000000  0.531146  0.000000   
doc4  0.277174  0.000000     0.000000      0.000000  0.000000  0.000000   

      studying     tracy   writing  
doc1  0.000000  0.255662  0.386261  
doc2  0.000000  0.255662  0.386261  
doc3  0.531146  0.277174  0.000000  
doc4  0.000000  0.277174  0.000000

In [25]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(data[0:1], data)

array([[1.        , 0.27992449, 0.14172606, 0.14172606]])